### ISSUE TITLE
TypeError: can only concatenate str (not "NoneType") to str

### ISSUE THREAD

**Issue by suikaremilia** [Vaayne/NotionAI-Plus#10]
HI, thanks for your work.
I updated the package to 0.1.0, and tried to test your example code.
```
$ pip list |grep notion
notionai-py          0.1.0    

$ cat test.py 
import os
from notionai import NotionAI

TOKEN = os.getenv("NOTION_TOKEN")
SPACE_ID = os.getenv("NOTION_SPACE_ID")

def main():
    ai = NotionAI(TOKEN, SPACE_ID)
    res = ai.blog_post("write a blog about the meaning of life")
    print(res)

if __name__ == "__main__":
    main()
```

And I set my NOTION_TOKEN and NOTION_SPACE_ID in the .env file
```
NOTION_TOKEN="xxx"
NOTION_SPACE_ID="yyy"
```

but I got an error:
```
$ python3 test.py 
Traceback (most recent call last):
  File "test.py", line 13, in <module>
    main()
  File "test.py", line 9, in main
    res = ai.blog_post("write a blog about the meaning of life")
  File "/home/a/notionai/.venv/lib/python3.8/site-packages/notionai/notionai.py", line 262, in blog_post
    return self.writing_with_topic(TopicEnum.blog_post, prompt)
  File "/home/a/notionai/.venv/lib/python3.8/site-packages/notionai/notionai.py", line 90, in writing_with_topic
    return self._post(content)
  File "/home/a/notionai/.venv/lib/python3.8/site-packages/notionai/notionai.py", line 59, in _post
    r = self._request(content)
  File "/home/a/notionai/.venv/lib/python3.8/site-packages/notionai/notionai.py", line 45, in _request
    "token_v2=" + self.token,
TypeError: can only concatenate str (not "NoneType") to str
```

It looks like the token was not set correctly. But I double-checked my token and confirmed that it was correct. I even set the relevant environment variables, but the error reporting persists.

**Comment by vaayne** [comment]
@suikaremilia Hi, can `export NOTION_TOKEN=xxx` and `export NOTION_SPACE_ID=yyy` manually, or use tools like [autoenv](https://github.com/hyperupcall/autoenv) or [direnv](https://github.com/direnv/direnv).

**Comment by suikaremilia** [comment]
I even registered a new notion account, but get the same error.

**Comment by suikaremilia** [comment]
I made a few attempts, including changing hosts, changing python versions, etc. Eventually found that defining the variables via export worked, nothing else did. Anyway it works now, thanks for your work.
