### ISSUE TITLE
There are some errors in the webui page

### ISSUE THREAD

**Issue by moeik** [Vaayne/NotionAI-Plus#11]
![image](https://user-images.githubusercontent.com/49871008/221130525-970c7398-870b-4f76-8ac4-83a749f77518.png)
![image](https://user-images.githubusercontent.com/49871008/221130619-3f832ae1-678a-474d-be9f-7a5fd6eec700.png)

During the use of my webui deployment, an error occurred and the content was not output correctly, and I have checked my account information filled in correctly several times.

**Comment by moeik** [comment]
![image](https://user-images.githubusercontent.com/49871008/221132803-356cb5a6-39d5-4962-b590-6f5e705f30be.png)

**Comment by vaayne** [comment]
<img width="315" alt="image" src="https://user-images.githubusercontent.com/10231735/221134822-eefca624-fc61-4756-bee1-2004b4878eeb.png">

You are misinterpreting the environment. Please just use it.
```
TOKEN="49...."
SPACE_ID="76..."
```

**Comment by moeik** [comment]
> <img alt="image" width="315" src="https://user-images.githubusercontent.com/10231735/221134822-eefca624-fc61-4756-bee1-2004b4878eeb.png">
> 
> You are misinterpreting the environment. Please just use it.
> 
> ```
> TOKEN="49...."
> SPACE_ID="76..."
> ```

How should I use this environment?

**Comment by moeik** [comment]
Thanks, he is working fine, but I'm not sure what to fill in the "Prompt" in the "Help me Write" section, and if it's for contextual use?
