### ISSUE TITLE
how long is the validity period of the token

### ISSUE THREAD

**Issue by sjpanysys746** [Vaayne/NotionAI-Plus#12]
Very good, would like to ask how long is the validity period of the token?

**Comment by sjpanysys746** [comment]
Is there a limit to the number of times a free user can use it?

**Comment by vaayne** [comment]
> Very good, would like to ask how long is the validity period of the token?

You could check your cookies, there is a expired time

**Comment by vaayne** [comment]
> Is there a limit to the number of times a free user can use it?

This just API, the rate limits are related to your own account

**Comment by sjpanysys746** [comment]
> related

Thank you, I understand, it seems that free users can only ask 20 questions.
