### ISSUE TITLE
 The UI design is hard to use

### ISSUE THREAD

**Issue by jarlin8** [Vaayne/NotionAI-Plus#16]
Chrome ：
![](https://testingcf.jsdelivr.net/gh/jarlin8/OSS@main/backup/167774005930011.jpg)

![](https://testingcf.jsdelivr.net/gh/jarlin8/OSS@main/backup/167774005630112.jpg)

**Comment by vaayne** [comment]
@jarlin8 I apologize for any inconvenience caused. I am currently learning to build web applications and this is my first frontend project. I will do my best to improve the user experience. 

Can you please provide me with your Chrome configuration? Are you using Dark Mode? Is your screen resolution low? If you can provide more information, I can better assist you.

**Comment by jarlin8** [comment]
thanks for your replying
yes ,I am using Dark Mode. Chrome version 110.0.5481.178 (64bit)  1920x1080

**Comment by vaayne** [comment]
@jarlin8 I have updated to a new version, but it is still being reviewed by the Chrome Web Store. However, you can install it offline. https://github.com/Vaayne/NotionAI/releases/tag/notion-plus-v0.0.7

**Comment by jarlin8** [comment]
thx boy！

**Comment by jarlin8** [comment]
I have already used the modified latest version, but there are still some problems. For example, when I enable the  Extension and open Twitter, I encounter the following situation:![](https://testingcf.jsdelivr.net/gh/jarlin8/OSS@main/backup/1677825586424twitter-123.jpg)

**Comment by vaayne** [comment]
@jarlin8 Still woking on this. Will fix in the next version
