### ISSUE TITLE
Not been working for me since update

### ISSUE THREAD

**Issue by JT-cyber** [Vaayne/NotionAI-Plus#17]
since before the most recent notion update I have been your unofficial API and it has been working amazingly. But since then when I try to generate a string using notion AI a blank string is returned: "", this was happening with my code but also your example code when I copied and pasted it.

**Comment by vaayne** [comment]
@JT-cyber Are you using the latest version? I'm not experiencing any issues with it. Could you please share your version, configuration, and how you are using it?

**Comment by JT-cyber** [comment]
thank you for responding, but I did some playing around and got it working. This is a very cool and useful project well done
