### ISSUE TITLE
Something went wrong (error code 402)

### ISSUE THREAD

**Issue by miztizm** [Vaayne/NotionAI-Plus#20]
BTW the version from Webstore gives me a **Something went wrong (error code 402).** 
The version from Githab also have this erorr.

 [image](https://user-images.githubusercontent.com/617020/222869216-5961947c-1c85-4185-bd36-b024dd3fe03d.png)

**Comment by vaayne** [comment]
@warshell  "402" indicates that you have not set the Notion space ID correctly. Please configure it in the options page.

**Comment by miztizm** [comment]
You are right bro, i was using another spaceId , there is so many different one.
