### ISSUE TITLE
Github switching to search input, instead of the extension when typing the letter s

### ISSUE THREAD

**Issue by miztizm** [Vaayne/NotionAI-Plus#21]
I wante to write the word **space**

![image](https://user-images.githubusercontent.com/617020/222869795-6214d5b1-e11f-407c-87d9-a36966e11288.png)

**Comment by vaayne** [comment]
@warshell, thank you for bringing up this issue. The problem is due to a default shortcut in GitHub. I will work on disabling this shortcut when typing in the input field.

As a workaround, you can input text in GitHub's text input and then copy it to NotionAI Plus. Thank you.

**Comment by vaayne** [comment]
fixed https://github.com/Vaayne/NotionAI-Plus/pull/40
