### ISSUE TITLE
[REQUEST] Some promising ideas (browser extension)

### ISSUE THREAD

**Issue by miztizm** [Vaayne/NotionAI-Plus#22]
First of all, thank you again. You can't imagine how useful I found it. <3 Here are some ideas:

- Full screen mode and left or right panel mode switcher with the last position remembered.
- Ability to drag the window.
- Option to copy the answer and paste it into the input, which is useful for modifying answers with a new prompt and improving them.
- Option to copy and paste into the current page's text area or input, which is useful for writing comments, answers, or emails.
- Default selection of the template.
- Separate selection for templates, as the list is too long. For example, languages could be separated.
- Ability to output in another language.
- Acting templates? (act as a coach, act as a professional trader etc)
- Coding templates? Improve the code, find problems, write comments, optimise, generate tests etc
- Adding a costume list of templates for the personal prompt input 
- Day/Night mode

ps: btw why is the source code that is in repo different from the production version? folder says 0.07 , chrome shows 0.05

**Comment by vaayne** [comment]
@warshell 
These are great ideas, thank you for using it and providing feedback. I will make a to-do list, but please note that I am currently developing a new feature, so it may take some time to complete. However, I will iterate on it as soon as possible.

Every new version submitted to the Chrome Web Store must be reviewed by the Chrome team, which can take several days. Therefore, the version available on the Chrome Web Store may differ from the version on GitHub. As we are in the early stages of development and actively making changes, it is difficult to keep everything in the same place.
