### ISSUE TITLE
Could not decrypt token.

### ISSUE THREAD

**Issue by date-0604** [Vaayne/NotionAI-Plus#24]
I followed the instructions on Github to obtain 
NOTION_TOKEN 
<img width="1440" alt="截圖 2023-03-06 上午5 36 31" src="https://user-images.githubusercontent.com/69830103/222987856-d519a797-d124-4771-aecd-78dce049fac6.png">

and NOTION_SPACE_ID, 
<img width="1440" alt="截圖 2023-03-06 上午5 53 04" src="https://user-images.githubusercontent.com/69830103/222988141-084d6336-79af-4efb-af51-4acbf802f8fd.png">

but when executing it, an error 'Could not decrypt token' appeared.
<img width="1440" alt="截圖 2023-03-06 上午5 37 58" src="https://user-images.githubusercontent.com/69830103/222988147-fdeef356-5f37-430e-8e76-5e684bd10ea0.png">

**Comment by vaayne** [comment]
@date-0604  have you tested it using the Python code example provided? Alternatively, could you show me your code so I can review it?

**Comment by date-0604** [comment]
This is my code.
<img width="1375" alt="截圖 2023-03-06 上午9 56 20" src="https://user-images.githubusercontent.com/69830103/223003404-dd4353b9-93be-4d09-bc7d-47c5b9bcbbec.png">

**Comment by vaayne** [comment]
@date-0604 It seems that your token is incorrect. Your token appears to be different from mine. Please try obtaining the token using Chrome.
here is how my token looks like
<img width="436" alt="image" src="https://user-images.githubusercontent.com/10231735/223010305-0006202f-d98f-4109-b9ae-8c401ed04e65.png">

**Comment by date-0604** [comment]
I use Chrome and his TOKEN looks very strange, it's different from yours.
<img width="1440" alt="截圖 2023-03-06 上午11 41 50" src="https://user-images.githubusercontent.com/69830103/223015313-3c73c0f6-71e6-41eb-874c-3dba16ea8655.png">

**Comment by vaayne** [comment]
@date-0604 I see, notion just change the token format, may be need some work on this

**Comment by vaayne** [comment]
@date-0604 hi, you should keeping all values in the token, starting from `v02` to `KLC`. Please retry, it should work

**Comment by date-0604** [comment]
Thank you, the code is now working properly!
