### ISSUE TITLE
请问填写的到底是NotionSpaceID还是NotionToken

### ISSUE THREAD

**Issue by FernandoChan** [Vaayne/NotionAI-Plus#26]
使用的时候提示 {"errorId":"f1418668-eb83-4701-a35c-f058a68fff04","name":"UnauthorizedError","message":"Token was invalid or expired.","clientData":{"type":"login_try_again"}}

请问是因为Notion AI达到了免费使用次数导致的吗？

**Comment by vaayne** [comment]
根据返回的信息，是你的 `Token` 不对
