### ISSUE TITLE
always say "NotionAI is not ready"

### ISSUE THREAD

**Issue by ulion** [Vaayne/NotionAI-Plus#27]
even configured everything.

**Comment by vaayne** [comment]
@ulion can you show more details about how you are configuring?

**Comment by ulion** [comment]
> @ulion can you show more details about how you are configuring?

![config](https://i.imgur.com/FRgd3wr.png)

and, even if filled openapi key,  still also same. and it should not rely on openai api key,  right? the notion space is notion ai paid account.

**Comment by vaayne** [comment]
Sorry about that. Please try the latest release at https://github.com/Vaayne/NotionAI/releases/tag/notionai-plus-v0.0.10 or wait for the Chrome version. Thank you.
