### ISSUE TITLE
Don't work on chrome

### ISSUE THREAD

**Issue by wonfull** [Vaayne/NotionAI-Plus#30]
I have set my notion space id and openai api key, but it doesn't work on chrome~
![image](https://user-images.githubusercontent.com/29720143/224550083-764e9428-4d74-4687-81fb-80a6575d1524.png)

**Comment by vaayne** [comment]
Sorry about that. Please try the latest release at https://github.com/Vaayne/NotionAI/releases/tag/notionai-plus-v0.0.10 or wait for the Chrome version. Thank you.
