### ISSUE TITLE
NotionAI is not ready

### ISSUE THREAD

**Issue by zh013** [Vaayne/NotionAI-Plus#31]
Hello, I have set the notion space id in the latest version 0.0.10, but it still doesn't work on edge, it says "NotionAI is not ready".
![image](https://user-images.githubusercontent.com/76717815/224659077-c2ba5e8b-5ed8-48aa-8dea-fdb0b3e2c3d8.png)
![image](https://user-images.githubusercontent.com/76717815/224660077-e5ff465f-a652-4bb6-8039-d559baf77701.png)
![image](https://user-images.githubusercontent.com/76717815/224660099-a3b40037-8947-4772-be5b-05eee58d8672.png)

**Comment by vaayne** [comment]
Hi, you can try it on the web page. I think everything is ready, but the right message is not being displayed.

**Comment by zh013** [comment]
You are right, thanks for your help
