### ISSUE TITLE
两个小建议，增加背景颜色和增加选项中文

### ISSUE THREAD

**Issue by NeezerGu** [Vaayne/NotionAI-Plus#32]
第一个是，只在谷歌上用没问题，因为右边是空白的，但当右边有东西的时候，比如我逛b站，右边就是各种视频，我就看不清notion ai的回复了（当然可以双击一下，就有底色勉强看）
第二个是，选项都是英文的。。讲真有点多还看不懂（好像比notion ai原生的还多？是我幻觉吗？）

另外感觉速度没用notion内置的快，可能是因为这里是必须全文输出完了之后一次性展示？所以显得久了？

**Comment by vaayne** [comment]
hi，多谢建议

> 第一个是，只在谷歌上用没问题，因为右边是空白的，但当右边有东西的时候，比如我逛b站，右边就是各种视频，我就看不清notion ai的回复了（当然可以双击一下，就有底色勉强看）
一直是有底色的，能否截个图看看？

> 第二个是，选项都是英文的。。讲真有点多还看不懂（好像比notion ai原生的还多？是我幻觉吗？）
多语言后续会加上的啊，应该很快了

> 速度没用notion内置的快
stream 格式的输出后续也会支持啊，暂时时间不大够

**Comment by NeezerGu** [comment]
以b站举例，我现在尝试看到长篇大论（当然不是这篇明显玩梗的），会尝试用notion ai 总结的功能：
![](<https://neezer.notion.site/image/https%3A%2F%2Fs3-us-west-2.amazonaws.com%2Fsecure.notion-static.com%2F86c63034-a659-4dbe-af3a-741d46af2813%2F1.png?id=438c6105-f93a-402e-b510-d8cae50026a8&table=block&spaceId=19d48e82-e4a2-4e6d-9223-d5433ad1ccb3&width=2000&userId=&cache=v2>)

但如上图，如果我想看清文字，必须要双击一下选中才能看清
![](<https://neezer.notion.site/image/https%3A%2F%2Fs3-us-west-2.amazonaws.com%2Fsecure.notion-static.com%2F17dfe956-bbff-47a5-bee3-ffeda3d8178d%2F2.png?id=3f0a77e3-8f42-4fa5-9adc-2210d3e6ed78&table=block&spaceId=19d48e82-e4a2-4e6d-9223-d5433ad1ccb3&width=2000&userId=&cache=v2>)

**Comment by vaayne** [comment]
<img width="1654" alt="image" src="https://user-images.githubusercontent.com/10231735/227817238-99e98fb9-abeb-4669-aef9-0c97d736229e.png">

@NeezerGu  不确定是什么原因导致的，这个默认都是有底色的，可能需要看一下你为什么没有了，你要不换一个浏览器试试。
也麻烦提供一下 浏览器版本和插件的版本，我好重现这个 bug

**Comment by NeezerGu** [comment]
我还在用这个链接底下的上古版本0.10
https://github.com/Vaayne/NotionAI-Plus/issues/27

刚刚发现都0.13了，尝试更新了下，结果反而用不了（0.13是有底色的，这个问题倒是解决了）。体现为选择notion引擎后，依旧问我要用什么引擎？
![](https://neezer.notion.site/image/https%3A%2F%2Fs3-us-west-2.amazonaws.com%2Fsecure.notion-static.com%2Fb773d433-795b-4842-8d9f-f0fc169fb649%2FWeChat%25E6%2588%25AA%25E5%259B%25BE_20230328021104.png?id=3c82dbc6-f186-4352-9229-1cd7117b2164&table=block&spaceId=19d48e82-e4a2-4e6d-9223-d5433ad1ccb3&width=2000&userId=&cache=v2)

我的浏览器版本是
![](https://neezer.notion.site/image/https%3A%2F%2Fs3-us-west-2.amazonaws.com%2Fsecure.notion-static.com%2Ffbe48843-d198-46cd-809f-5e30dda7760c%2FWeChat%25E6%2588%25AA%25E5%259B%25BE_20230328021414.png?id=2b60722f-5eb9-4ee2-ae60-468a2e5b88fd&table=block&spaceId=19d48e82-e4a2-4e6d-9223-d5433ad1ccb3&width=2000&userId=&cache=v2)

我能找到的可能跟错误有关的信息是
![](https://neezer.notion.site/image/https%3A%2F%2Fs3-us-west-2.amazonaws.com%2Fsecure.notion-static.com%2Fd1f7f1f8-cf41-4f1a-9bc8-19771294d76f%2FWeChat%25E6%2588%25AA%25E5%259B%25BE_20230328021315.png?id=c42075ae-b5b3-42aa-880c-571af7fc4af9&table=block&spaceId=19d48e82-e4a2-4e6d-9223-d5433ad1ccb3&width=2000&userId=&cache=v2)
![](https://neezer.notion.site/image/https%3A%2F%2Fs3-us-west-2.amazonaws.com%2Fsecure.notion-static.com%2Fc93b4b5c-e555-4222-86f1-d171fd47ccbc%2FWeChat%25E6%2588%25AA%25E5%259B%25BE_20230328021044.png?id=d6b1681f-6698-4efd-b135-639dbddc2e3c&table=block&spaceId=19d48e82-e4a2-4e6d-9223-d5433ad1ccb3&width=2000&userId=&cache=v2)

**Comment by vaayne** [comment]
我试了一下，确实是这样的，应该是 Engine 初始化的时候没有成功，这个错误和初始化 Engine 是没有问题的，不过也应该 Fix

**Comment by vaayne** [comment]
@NeezerGu 你可以使用最新版的测试一下

**Comment by NeezerGu** [comment]
> @NeezerGu 你可以使用最新版的测试一下

可以了，感谢大佬
