### ISSUE TITLE
"continue writing" not work for notion API

### ISSUE THREAD

**Issue by zhanglei1172** [Vaayne/NotionAI-Plus#34]
when I use web extension with "continue writing" prompt, it response "Please provide content to insert here."

**Comment by vaayne** [comment]
Hi, which version of the software are you using? Could you kindly provide a screenshot, please?

**Comment by zhanglei1172** [comment]
![image](https://user-images.githubusercontent.com/34906782/227779854-b8abbbf6-a533-43c2-9363-d5ef80d5856d.png)

extension version: 0.0.10
browser: Edge 112.0.1722.17(dev arm64)
os: macos 12.6.3
chip: M1

**Comment by vaayne** [comment]
Thank you, I will take a look .

**Comment by NeezerGu** [comment]
I found out and thought it was a wrong function. 
At Notion, it can be used when you have some words and want more, but now you don't have any.

**Comment by vaayne** [comment]
<img width="566" alt="image" src="https://user-images.githubusercontent.com/10231735/227817070-3c871586-a4b3-44fa-bb71-606ae90ce68e.png">

@NeezerGu  @zhanglei1172  This issue will be fixed in the next version. Thank you for bringing it to our attention.
