### ISSUE TITLE
shortcut to hide panel

### ISSUE THREAD

**Issue by zhanglei1172** [Vaayne/NotionAI-Plus#38]
Hi, I found that the latest version of the extension cannot use the shortcut key command+ k to **hide** the extension, I think this is a very practical feature, I hope it can be added.

**Comment by vaayne** [comment]
Okay, currently we have a function to hide the extension using ESC. However, I disabled the shortcut so you can select text when the extension is open. I'm not sure which approach is more reasonable. 

Maybe we discuss and decide on the better option?
