### ISSUE TITLE
res is not defined

### ISSUE THREAD

**Issue by WianVermaak** [Vaayne/NotionAI-Plus#43]
![image](https://github.com/Vaayne/NotionAI-Plus/assets/135003658/213e9b40-d19e-44b1-8b3e-94e60336a61c)

How do I fix this error?

**Comment by vaayne** [comment]
@WianVermaak, I have resolved this issue in the most recent version. You can find the fix in the latest commit on GitHub https://github.com/Vaayne/NotionAI-Plus/commit/fd3bf4fe90637d6c4b9e3f0912aba033cf8470ae

Please be patient for the update to be available on the Chrome Web Store, or alternatively, you can manually install it from the release.

**Comment by WianVermaak** [comment]
Hi Vaayne

Apologies, but I was not able to find out how to install it manually from
the release.

Do you perhaps have a link to show how to do this?

**Comment by WianVermaak** [comment]
Oh nevermind! It is working now!

Thanks for this magic.

**Comment by WianVermaak** [comment]
Hi Vaayne

I'm sorry to bug you, but can I ask a silly question?

Once I've brought up the Notion block, how do I then get rid of it or
minimise it? Currently I am refreshing the page to get rid of it once I
have my info from Notion.

I know this is not for you to answer, but please help I feel stupid.

I'm also not wondering if these emails actually send?

Kind regards
Wian

**Comment by vaayne** [comment]
> Hi Vaayne I'm sorry to bug you, but can I ask a silly question? Once I've brought up the Notion block, how do I then get rid of it or minimise it? Currently I am refreshing the page to get rid of it once I have my info from Notion. I know this is not for you to answer, but please help I feel stupid. I'm also not wondering if these emails actually send? Kind regards Wian
> […](#)

just press ESC
