### ISSUE TITLE
'res is not defined' Error

### ISSUE THREAD

**Issue by JTDimino** [Vaayne/NotionAI-Plus#44]
I'm trying to use the NotionAI engine to brainstorm ideas on a text selection (already set up my Space in Options), but I am getting a 'res is not defined' error.

**Comment by vaayne** [comment]
@JTDimino same as https://github.com/Vaayne/NotionAI-Plus/issues/43

**Comment by vaayne** [comment]
@JTDimino Please upgrade to the latest version.
