### ISSUE TITLE
some questions about the chatgptweb engine

### ISSUE THREAD

**Issue by animebing** [Vaayne/NotionAI-Plus#45]
Thanks for this great extension. In the notionai-plus extension, my default engine is chatgpt web and it works well, but one question confuses me a lot: I do not login to my chatgpt account(I log out first), but i still works. I am looking forward to your reply.

**Comment by vaayne** [comment]
That's weird. You can open the DevTools by following the screenshot and then checking the Network tab to view the requests.

<img width="1723" alt="image" src="https://github.com/Vaayne/NotionAI-Plus/assets/10231735/c14f0867-1473-47af-a5a6-c3710909d2f0">

**Comment by animebing** [comment]
I have checked the network tab as you say, I find at the time when I first quit ChatGPT, the plugin did not make a call to https://chat.openai.com/api/auth/session to obtain an access token, It used the cache within the plugin. However, after some time passed and I went to use the plugin again, it attempted to call https://chat.openai.com/api/auth/session, but returned a 401 UNAUTHORIZED

**Comment by vaayne** [comment]
That makes sense
