### ISSUE TITLE
第二次触发插件

### ISSUE THREAD

**Issue by PrayerLi** [Vaayne/NotionAI-Plus#46]
设置好快捷键后，在页面上选中文字触发快捷键可以激活扩展，但是如果我这个时候选中另一段文字再点击快捷键，扩展就没反应了

**Comment by vaayne** [comment]
这应该是个 bug，我看看为啥然后 fix 一下，我之前是可以多次选择的

你可以先按 ESC 隐藏，然后重新激活

**Comment by PrayerLi** [comment]
好的，谢谢
