### ISSUE TITLE
Cannot be used

### ISSUE THREAD

**Issue by helloxz** [Vaayne/NotionAI-Plus#5]
Notion recently started charging, and free users can only experience it 20 times, which has been working well before, but the recent call code returned null.

**Comment by vaayne** [comment]
Notion just update it's API, I am fixing it.

**Comment by helloxz** [comment]
Thank you for your efforts. I'm waiting for your good news.

**Comment by vaayne** [comment]
@helloxz The Python SDK is working now. Give it a try!

**Comment by helloxz** [comment]
You can work again. Thank you for your service.
