### ISSUE TITLE
question

### ISSUE THREAD

**Issue by Zarahhhhhh** [Vaayne/NotionAI-Plus#51]
Sorry to bother someone...there is something wrong with my notionAI Plus, i want to know, if i don't pay for notionAI, can i use the service from notionAI plus? i had to try to use its service, there is no response...sad.

**Comment by Zarahhhhhh** [comment]
> Sorry to bother someone...there is something wrong with my notionAI Plus, i want to know, if i don't pay for notionAI, can i use the service from notionAI plus? i had to try to use its service, there is no response...sad.

that is to say, i can see the menu but i can't use any of them,which made me sad enough

**Comment by vaayne** [comment]
Support multiple engines:

Free:
[ChatGPT Web](https://chat.openai.com/)
[New Bing](https://www.bing.com/new)
[Brad](https://bard.google.com/)
[Claude](https://claude.ai/)
Paid:
[NotionAI](https://www.notion.so/product/ai)
[ChatGPT API](https://platform.openai.com/docs/api-reference/chat/create)


You can try using ChatGPT Web, New Bing, Brad for free by logging into their respective websites. Once you have access, you can try using them with NotionAI Plus.

**Comment by vaayne** [comment]
I mostly rely on the ChatGPT API as it is most stable. @Zarahhhhhh

**Comment by Zarahhhhhh** [comment]
Thank you,Vaayne. I had overlooked the note FREE and PAID.
But i try using chatgptweb just now. Nothing is changed. The button "enter" the function to engender is constantly rotating. i was crazy,hhh. thanks for your reply
