### ISSUE TITLE
Notion AI api broken down

### ISSUE THREAD

**Issue by zhanglei1172** [Vaayne/NotionAI-Plus#58]
All apis return `NotionAI return error, status: 400`. Perhaps the notion API changed.

**Comment by vaayne** [comment]
@zhanglei1172 Fix it in the latest [commit](https://github.com/vaayne/NotionAI-Plus/commit/3f8c7c9aa6b2761a34daee472025b035f7a94829). Please wait for the Chrome store to update, or you can download it from the release and load it manually.

**Comment by vaayne** [comment]
I will close this issue as it was fixed.
