### ISSUE TITLE
not found spaceId

### ISSUE THREAD

**Issue by helloxz** [Vaayne/NotionAI-Plus#8]
Hello, I described the operation according to your document, but I couldn't find spaceid

![image](https://user-images.githubusercontent.com/7276531/220867774-4af52b8c-a486-40fc-aa3a-066c88b981c9.png)

**Comment by vaayne** [comment]
Could you please try refreshing the page and attempting again? If you are still experiencing issues, you may want to try locating the content from the network.

<img width="1134" alt="image" src="https://user-images.githubusercontent.com/10231735/220872336-2c9270eb-3a5b-463c-b7e3-46f07dba8de0.png">

**Comment by helloxz** [comment]
Thank you very much. I found spaceId through this screenshot you provided. It is now available. Thank you for your hard work.
