### ISSUE TITLE
I got a error message

### ISSUE THREAD

**Issue by 4111y80y** [Vaayne/NotionAI-Plus#9]
data: {"errorId":"a4d63819-215e-430c-9ea9-ce7e451bf284","name":"ValidationError","message":"Invalid input."}, error: 'type'

**Comment by vaayne** [comment]
Could you provide more detail? Which version of Notion AI are you referring to? How are you using it?

**Comment by 4111y80y** [comment]
Looking in indexes: http://pypi.douban.com/simple/
Requirement already satisfied: notionai-py in d:\anaconda3\envs\flagai\lib\site-packages (0.0.9)
Requirement already satisfied: requests in d:\anaconda3\envs\flagai\lib\site-packages (from notionai-py) (2.28.1)
Requirement already satisfied: charset-normalizer<3,>=2 in d:\anaconda3\envs\flagai\lib\site-packages (from requests->notionai-py) (2.1.1)
Requirement already satisfied: certifi>=2017.4.17 in d:\anaconda3\envs\flagai\lib\site-packages (from requests->notionai-py) (2022.12.7)
Requirement already satisfied: idna<4,>=2.5 in d:\anaconda3\envs\flagai\lib\site-packages (from requests->notionai-py) (3.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in d:\anaconda3\envs\flagai\lib\site-packages (from requests->notionai-py) (1.26.13)



import os
import sys
from notionai import NotionAI, NotionAIStream, PromptTypeEnum, TopicEnum

TOKEN = "???"
SPACE_ID = "???"


def main():
    ai = NotionAI(TOKEN, SPACE_ID)
    res = ai.writing_with_topic(TopicEnum.blog_post, "Please help to introduce Notion")
    print(res)

if __name__ == "__main__":
    main()


result:
data: {"errorId":"5f89d697-9d73-4445-a6e1-063a16fd0e11","name":"ValidationError","message":"Invalid input."}, error: 'type'


Process finished with exit code 0

**Comment by 4111y80y** [comment]
I upgrade to v0.1.0，It's worded. thank you.
